#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
try {
    $dotenv->load();
    // Debug: Log loaded environment variables
    //error_log(print_r($_ENV, true));
} catch (Dotenv\Exception\InvalidPathException $e) {
    die('The .env file is missing or invalid.');
}

// Debug: Check loaded environment variables
$dotenv->required(['DB_DSN', 'DB_USERNAME', 'DB_PASSWORD'])->notEmpty();
$dotenv->required(['YII_DEBUG', 'YII_ENV'])->allowedValues(['true', 'false', 'dev', 'prod']);

// Explicitly set environment variables using putenv()
foreach ($_ENV as $key => $value) {
    putenv("$key=$value");
}

$config = require __DIR__ . '/config/console.php';
(new yii\console\Application($config))->run();